language: go

go:
  - 1.13

os:
  - linux

git:
  depth: 1

before_install:
  - go get -u

script:
  - cd $TRAVIS_BUILD_DIR
  - ./build.sh

notifications:
  email: false

deploy:
  provider: releases
  api_key: $RELEASE_API_KEY
  file:
    - build/sypht-cli-darwin-amd64.zip
    - build/sypht-cli-windows-386.zip
    - build/sypht-cli-windows-amd64.zip
  skip_cleanup: true
  on:
    tags: true
