language: go

go:
  - 1.13

os:
  - linux

git:
  depth: 1

before_install:
  - go get -u

script:
  - cd $TRAVIS_BUILD_DIR
  - ./build.sh

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: $RELEASE_API_KEY
  file: build/assets.zip
  skip_cleanup: true
  on:
    tags: true
